Only create postgres_db if not using external
Tecnativa/doodba-copier-template pull request #150
Opened 2020-10-22 06:49 UTC by joao-p-marques

Fixes https://github.com/Tecnativa/doodba-copier-template/issues/148

2020-10-22 09:49 UTC, Yajo commented on common.yaml.jinja
> +  {%- if postgres_version is not none %}
You can simplify this, here and in all others:

```suggestion
  {%- if postgres_version %}
```

2020-10-22 10:55 UTC, Yajo requested changes

2020-10-22 10:55 UTC, Yajo commented on devel.yaml.jinja
> +  {%- if postgres_version is not none %}
```suggestion
  {%- if postgres_version %}
```

2020-10-22 10:55 UTC, Yajo commented on prod.yaml.jinja
> +  {%- if postgres_version is not none %}
```suggestion
  {%- if postgres_version %}
```

2020-10-22 10:55 UTC, Yajo commented on test.yaml.jinja
> +  {%- if postgres_version is not none %}
```suggestion
  {%- if postgres_version %}
```

2020-10-22 10:56 UTC, merged

2020-10-28 03:26 UTC, ska-ibees commented
odoo@ubuntu20:~/Docker/dock13$ invoke img-pull
Reinitialized existing Git repository in /home/odoo/Docker/dock13/.git/
pre-commit installed at .git/hooks/pre-commit
Service 'odoo' depends on service 'db' which is undefined.

2020-10-28 03:27 UTC, ska-ibees commented
Can we have 'DATABASE_URL' in copier question to get some flexibility? Like I intend to deploy Doodba on AWS EC2 by connecting it to AWS RDS database (Over network).