Debugger fixes and improvements
Tecnativa/doodba-copier-template pull request #176
Opened 2020-11-11 16:00 UTC by joao-p-marques

1. Map Python debugger to odoo/auto: All Odoo addons and core code are now mapped individually with the Python debugger.
2. Enable logs for test task when not in debug mode
3. Improve error messages

Error handling can still be improved, by trying to integrate better with VSCode tasks errors, but I had no success so far.

TT26728

2020-11-12 09:03 UTC, Yajo requested changes

2020-11-12 10:54 UTC, joao-p-marques commented
Changes made @Yajo 

I had to test other addons to include other cases, but I tried to keep it simple and light, and test and install tasks are now tested together.

I also ended up ignoring the return code from the tests, so that our CI never fails because of some bad integration errors upstream, as has happened with https://github.com/Tecnativa/doodba-copier-template/runs/1389417193?check_suite_focus=true#step:14:988

2020-11-12 11:09 UTC, Yajo requested changes
Almost there

2020-11-12 11:09 UTC, Yajo commented on tests/test_tasks_downstream.py
>              )
I think this'd be important:

```suggestion
            )
            assert "devel odoo.modules.loading: All post-tested" in stdout
```

2020-11-12 11:09 UTC, Yajo commented on tests/test_tasks_downstream.py
>              )
Here too:

```suggestion
            )
            assert "devel odoo.modules.loading: All post-tested" in stdout
```

2020-11-12 12:23 UTC, Yajo commented
Review the failure. Maybe the test is wrong or maybe odoo is really not testing the addons.

2020-11-12 12:25 UTC, joao-p-marques commented
Yes, I am already on it. Seems like the correct log is
```
devel odoo.service.server: All post-tested
```
OTOH, I am also getting different logs in v14. I am investigating if this logs change between versions...

2020-11-13 08:24 UTC, Yajo commented
> I am investigating if this logs change between versions...

Most probably yes, because I copied https://github.com/Tecnativa/doodba-copier-template/pull/176#discussion_r522024064 from v12.

2020-11-13 08:26 UTC, joao-p-marques commented
Yes, I ended up creating the `_tests_ran` function to check specific logs base on the current version. Let's see if it works for all the versions.

2020-11-13 09:45 UTC, Yajo approved these changes

2020-11-13 09:56 UTC, joao-p-marques commented on tests/test_tasks_downstream.py
> +            assert _tests_ran(stdout, supported_odoo_version, "note")
If you are doing `assert`s in the _tests_ran function, this needs to be adapted. Either return true or false in the function, or just do a normal call here.

2020-11-13 09:58 UTC, joao-p-marques commented
Just a small doubt... Otherwise tests look much better now, thank you!

2020-11-13 13:14 UTC, merged