[FIX] Correct always using docker compose, even if it not compatible.
Tecnativa/doodba-copier-template pull request #464
Opened 2024-04-10 09:51 UTC by josep-tecnativa

In this change https://github.com/Tecnativa/doodba-copier-template/commit/e2bc946fa20edc34e9007c40c3d41e0491710fca is always used docker compose. In docker versions 24.0.6 or lower, this is incompatible, and needs to use docker-compose

2024-04-10 10:05 UTC, chienandalu requested changes

2024-04-10 10:05 UTC, chienandalu commented on tasks_downstream.py
> +    [which("docker"), "compose"], capture_output=True, text=True
This parameter isn't needed really
```suggestion
    [which("docker"), "compose"], capture_output=True
```

2024-04-10 10:05 UTC, chienandalu commented on tasks_downstream.py
>  )
```suggestion
docker_compose_v2 = subprocess.run(
    [which("docker"), "compose"], capture_output=True
).returncode == 0
```

2024-04-10 10:05 UTC, chienandalu commented on tasks_downstream.py
> +    DOCKER_COMPOSE_CMD = "docker-compose"
You need the whole path to run the commands
```suggestion
DOCKER_COMPOSE_CMD = f"{shutil.which('docker')} compose" if docker_compose_v2 0 else  shutil.which(
    "docker-compose"
```

2024-04-10 10:51 UTC, chienandalu requested changes

2024-04-10 10:51 UTC, chienandalu commented on tasks_downstream.py
> +    subprocess.run([which("docker"), "compose"], capture_output=True).returncode == 0
Don't take my word for granted :sweat_smile: 
```suggestion
    subprocess.run([shutil.which("docker"), "compose"], capture_output=True).returncode == 0
```

2024-04-10 10:51 UTC, chienandalu commented on tasks_downstream.py
> +
```suggestion
# Document the code here :smile: 
```

2024-04-10 10:51 UTC, chienandalu commented on tasks_downstream.py
> +
```suggestion
```

2024-04-10 12:05 UTC, chienandalu requested changes
The commit message isn't very helpful. What about:

[FIX] docker compose command fallback

2024-04-10 12:05 UTC, chienandalu commented on tasks_downstream.py
> +# it will use this; otherwise, it will fallback to using docker-compose instead.
Be more concise :) Also explain why
```suggestion
# Depending on the user's docker version either version of docker compose could not be available. We default to v2 and fallback to v1.
```

2024-04-11 11:52 UTC, chienandalu approved these changes
:+1: Although now tests are red :thinking:

2024-04-12 05:57 UTC, josep-tecnativa commented
Seems like the odd CI error is due to the line being too long, but no error is triggered in the local `pre-commit run -a`.

2024-04-12 06:12 UTC, merged